"""Operational TRACE — stages canónicos (fatia A)."""

from __future__ import annotations

# Kernel
KERNEL_REQUEST_RECEIVED = "REQUEST_RECEIVED"
KERNEL_IDEMPOTENCY_CHECK = "IDEMPOTENCY_CHECK"
KERNEL_TRANSCRIPT_LOADED = "TRANSCRIPT_LOADED"
KERNEL_PIN_LOADED = "PIN_LOADED"
KERNEL_GROUP_MEMORY_LOOKUP = "GROUP_MEMORY_LOOKUP"
KERNEL_GROUP_PROFILE_LOADED = "GROUP_PROFILE_LOADED"
KERNEL_TEMPORAL_CONTEXT = "TEMPORAL_CONTEXT"
KERNEL_CALENDAR_LOOKUP = "CALENDAR_LOOKUP"
KERNEL_RAG_STARTED = "RAG_STARTED"
KERNEL_RAG_FINISHED = "RAG_FINISHED"
KERNEL_LLM_STARTED = "LLM_STARTED"
KERNEL_LLM_FINISHED = "LLM_FINISHED"
KERNEL_PROMPT_BUILT = "PROMPT_BUILT"
KERNEL_RESPONSE_GENERATED = "RESPONSE_GENERATED"
KERNEL_RESPONSE_RETURNED = "RESPONSE_RETURNED"
KERNEL_ERROR = "ERROR"

# Orbit (ingest)
ORBIT_MESSAGE_RECEIVED = "MESSAGE_RECEIVED"
ORBIT_MESSAGE_PARSED = "MESSAGE_PARSED"
ORBIT_REQUEST_SENT = "REQUEST_SENT_TO_KERNEL"
ORBIT_RESPONSE_RECEIVED = "RESPONSE_RECEIVED_FROM_KERNEL"
ORBIT_MESSAGE_SENT = "MESSAGE_SENT_TO_WHATSAPP"
ORBIT_ERROR = "ERROR"

SERVICE_KERNEL = "kernel"
SERVICE_ORBIT = "orbit"

PRIORITY_ERROR = 0
PRIORITY_NORMAL = 10
