- uses: lowlighter/metrics@latest
        with:
          filename: kernel-status.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }} # Necessário para o push automático
          user: GaabDevWeb
          repo: KernelBot
          template: classic
          base: "" 
          config_timezone: America/Sao_Paulo
          config_twotone: yes
          config_display: large

          # Foco em Linguagem e Complexidade (Arquitetura do Kernel)
          plugin_languages: yes
          plugin_languages_details: lines, percentage
          plugin_languages_indepth: yes
          
          # Foco em Engenharia e Workflow (Gestão de Branches/PRs)
          plugin_lines: yes
          plugin_followup: yes
          plugin_followup_sections: repositories
          
          # Atividade e Ritmo (Visual de "Dashboard" Industrial)
          plugin_habits: yes
          plugin_habits_charts: yes # Gera os gráficos de barras sólidos
          plugin_habits_trim: yes
          
          # Tráfego (Interesse no Repositório)
          plugin_traffic: yes
