name: Metrics
on:
  # Agenda para rodar todo dia à meia-noite
  schedule: [{cron: "0 0 * * *"}]
  # Permite que você rode manualmente na aba Actions
  workflow_dispatch:
  # Opcional: roda sempre que você der push na main
  push: {branches: ["master", "main"]}

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          user: GaabDevWeb  
          template: classic
          base: header, activity, community, repositories
          config_timezone: America/Sao_Paulo
          
          config_twotone: yes
          config_display: large
          
          plugin_lines: yes
          
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_charts: yes
          plugin_habits_trim: yes
          
          # CONFIGURAÇÃO DE OUTPUT
          filename: github-metrics.svg
